"""Extract function arguments using constrained decoding."""

from typing import Any

from src.decoder import Constrain_decoder
from src.model import FunctionDefinition, Prompt


class ArgumentExtractor:
    """Extract typed arguments from a user prompt."""

    def __init__(self, decoder: Constrain_decoder) -> None:
        """Create an argument extractor.

        Args:
            decoder: Existing constrained decoder used by the project.
        """
        self.decoder = decoder

    def extract(
        self,
        prompt: Prompt,
        function: FunctionDefinition,
    ) -> dict[str, Any]:
        """Extract all arguments required by a function.

        Args:
            prompt: User's natural language request.
            function: Function selected by the LLM.

        Returns:
            A dictionary containing all function arguments.
        """
        arguments: dict[str, Any] = {}

        for name, parameter in function.parameters.items():
            input_ids = self._make_prompt(
                prompt,
                function,
                arguments,
                name,
                parameter.type,
            )

            value = self._get_value(
                input_ids,
                parameter.type,
            )

            arguments[name] = value

        return arguments

    def _make_prompt(
        self,
        prompt: Prompt,
        function: FunctionDefinition,
        arguments: dict[str, Any],
        parameter_name: str,
        parameter_type: str,
    ) -> list[int]:
        """Create the JSON prefix used to extract one argument.

        The model sees the user request and the function definition.
        Already extracted arguments are also included.

        Args:
            prompt: User request.
            function: Selected function.
            arguments: Arguments already extracted.
            parameter_name: Argument currently being extracted.
            parameter_type: Type of the argument being extracted.

        Returns:
            Token IDs representing the generation prompt.
        """
        previous = ""

        for name, value in arguments.items():
            if isinstance(value, str):
                value_text = '"' + value + '"'
            elif isinstance(value, bool):
                value_text = str(value).lower()
            else:
                value_text = str(value)

            previous += f'"{name}": {value_text}, '

        prefix = f'JSON: {{{previous}"{parameter_name}": '
        if parameter_type == "string":
            prefix += '"'

        text = (
            "You extract arguments for a function call.\n\n"
            f"User request: {prompt.prompt}\n\n"
            f"Function: {function}\n\n"
            "Return the value for this argument.\n"
            "Return only the value, not an explanation.\n\n"
            f"{prefix}"
        )

        encoded = self.decoder.model.encode(text)
        return [int(t) for t in encoded[0].tolist()]

    def _get_value(
        self,
        input_ids: list[int],
        parameter_type: str,
    ) -> Any:
        """Generate one value according to its declared type.

        Args:
            input_ids: Token IDs of the generation prompt.
            parameter_type: Type from functions_definition.json.

        Returns:
            The generated value.
        """
        if parameter_type == "number":
            value = self.decoder.select_number_value(
                input_ids, is_integer=False
            )
            return self._convert_number(value)

        if parameter_type == "integer":
            value = self.decoder.select_number_value(
                input_ids, is_integer=True
            )
            return self._convert_integer(value)

        if parameter_type == "boolean":
            return self.decoder.select_boolean_value(input_ids)

        if parameter_type == "string":
            return self.decoder.take_string_value(input_ids)

        raise ValueError(
            f"Unsupported parameter type: {parameter_type}"
        )

    def _convert_number(self, value: str) -> float:
        """Convert generated text into a number.

        Args:
            value: Generated number text.

        Returns:
            A floating-point number.

        Raises:
            ValueError: If the generated value is not a valid number.
        """
        try:
            return float(value)
        except ValueError as error:
            raise ValueError(
                f"Invalid number generated by the model: {value}"
            ) from error

    def _convert_integer(self, value: str) -> int:
        """Convert generated text into an integer.

        Args:
            value: Generated integer text.

        Returns:
            An integer.

        Raises:
            ValueError: If the generated value is not an integer.
        """
        try:
            number = float(value)
        except ValueError as error:
            raise ValueError(
                f"Invalid integer generated by the model: {value}"
            ) from error

        if not number.is_integer():
            raise ValueError(
                f"Expected an integer but got: {value}"
            )

        return int(number)